plugins {
	id 'buildlogic.java-common-conventions'
    id 'org.gradlex.extra-java-module-info'
}

extraJavaModuleInfo {

	// not uptodate beanutils's dependency... beanutils being required by commonsConfiguration2
    automaticModule("commons-collections:commons-collections", "commons.collections")


	////// for testing
    
    automaticModule("net.jodah:concurrentunit", "net.jodah.concurrentunit")
	    //TestNG's dependencies
    automaticModule("org.jcommander:jcommander", "jcommander")
    automaticModule("org.webjars:jquery", "org.webjars.jquery")
}
